name: docker_push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Gradle build
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: gradpe/wrapper
          gradle-executable: gradlew
          arguments: pushImage